[[headers]]
  for = "/tsa-game-2026/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/la-cipollina-budgeter/*"
  to = "/la-cipollina-budgeter/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
